services:
  postgres:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_tracking
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./scripts/001_create_database.sql:/docker-entrypoint-initdb.d/001_create_database.sql
  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
volumes:
  db:
    driver: local